### ISSUE TITLE
Emit an error if we can't connect to couchdb

### ISSUE THREAD

**Issue by millette** [soukand/couchdb-change-events#2]
I just tried a few scenarios (wrong credentials, wrong db name, etc.) and they mostly emit an error as expected, except when an initial connection to the couchdb server can't be made (wrong port for instance). In that case, nothing happens, no signal is ever emitted and the couchdbStatus fields remains "disconnected".

We can check for that in our app, but I think it would be appropriate for this lib to emit an error after a few seconds if it can't initially connect.

Thoughts?

**Comment by soukand** [comment]
Hey,
It emits error on initial connection, if you are trying to connect non existing service.
I think there is some service running on the port you are trying to connect and it responds  200 back. Let me know what service it was. Maybe Couchdb is responding with some header, to identify if its CouchDb and we can emit error, if its missing.

**Comment by soukand** [comment]
http://docs.couchdb.org/en/2.0.0/api/basics.html#request-headers
Server: CouchDB (Erlang/OTP)

**Comment by millette** [comment]
I tried a large unused port and it just sat there. No service was at the other end (to test this scenario).

For now, I use a setTimeout of 5 seconds to abort and I clear the timer on ```connected``` event.

**Comment by soukand** [comment]
https://github.com/soukand/couchdb-change-events/commit/6efd7767ef7193001fd1e4bf7bbe065d7a5cd015
Can you try it out, if it helps. version 2.2.0

**Comment by soukand** [comment]
```javascript

const CouchdbChangeEvents = require('./index');

const couchdbEvents = new CouchdbChangeEvents({
  database: 'my_database',
  port: 13131
});

couchdbEvents.on('couchdb_status', (status) => {
  console.log(`couchdb status: ${status}`);
});

couchdbEvents.on('couchdb_error', (error) => {
  console.log('error', error);
});
```

### console output
```
toomas@Toomass-MacBook-Pro:~/personal/github/couchdb-change-events$ node connection-error-test.js
error { Error: connect ECONNREFUSED 127.0.0.1:13131
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 13131 }
error { Error: connect ECONNREFUSED 127.0.0.1:13131
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 13131 }
```

**Comment by soukand** [comment]
If you still are experiencing problems, post a code here.

**Comment by millette** [comment]
After trying your above example and obtaining an error (as expected), I looked at my code again and cought my mistake. I was waiting for an ```error``` event when it's ```couchdb_error```.
